apiVersion: v1
kind: Namespace
metadata:
  name: flask-space

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: flask-space
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: summaryexperts/flask-frontend:1.0.0
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: flask-space
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer